defmodule FoodTruckTest do
  use ExUnit.Case

  test "it returns a list of matching food trucks" do
    response = FoodTruck.search("taco", 37.7749, -122.4194, 10)
    assert response == [
             %FoodTruck{applicant: "Senor Sisig", facility_type: "Truck", location_description: "ELLIS ST: POWELL ST to CYRIL MAGNIN ST (100 - 148)", address: "120 ELLIS ST", dayshours: "", food_items: "Filipino fusion food: taco: burrito: nachos: rice plates", latitude: "37.78561008636915", longitude: "-122.40815476434545", schedule: "http://bsm.sfdpw.org/PermitsTracker/reports/report.aspx?title=schedule&report=rptSchedule&params=permit=22MFF-00044&ExportPDF=1&Filename=22MFF-00044_schedule.pdf", status: "APPROVED"},
             %FoodTruck{applicant: "Senor Sisig", facility_type: "Truck", location_description: "10TH ST: FELL ST \\ MARKET ST \\ POLK ST to STEVENSON ST (1 - 18)", address: "8 10TH ST", dayshours: "", facility_type: "Truck", food_items: "Senor Sisig: Filipino fusion food: tacos: burritos: nachos: rice plates. Various beverages.Chairman Bao: Vegetable and meat sandwiches filled with Asian-flavored meats and vegetables.", latitude: "37.7758255197583", longitude: "-122.41724962664345", schedule: "http://bsm.sfdpw.org/PermitsTracker/reports/report.aspx?title=schedule&report=rptSchedule&params=permit=22MFF-00046&ExportPDF=1&Filename=22MFF-00046_schedule.pdf", status: "APPROVED"},
             %FoodTruck{applicant: "Senor Sisig", facility_type: "Truck", location_description: "BROADWAY: DAVIS ST to FRONT ST (50 - 99)", address: "90 BROADWAY", status: "APPROVED", food_items: "Senor Sisig: Filipino fusion food: tacos: burritos: nachos: rice plates. Various beverages.Chairman Bao: Vegetable and meat sandwiches filled with Asian-flavored meats and vegetables.", latitude: "37.799260113502285", longitude: "-122.39961794865545", schedule: "http://bsm.sfdpw.org/PermitsTracker/reports/report.aspx?title=schedule&report=rptSchedule&params=permit=22MFF-00046&ExportPDF=1&Filename=22MFF-00046_schedule.pdf", dayshours: ""},
             %FoodTruck{applicant: "Senor Sisig", facility_type: "Truck", location_description: "02ND ST: MISSION ST to MINNA ST (100 - 130)", address: "120 02ND ST", status: "APPROVED", food_items: "Filipino fusion food: taco: burrito: nachos: rice plates", latitude: "37.787514060738104", longitude: "-122.39956633142907", schedule: "http://bsm.sfdpw.org/PermitsTracker/reports/report.aspx?title=schedule&report=rptSchedule&params=permit=22MFF-00044&ExportPDF=1&Filename=22MFF-00044_schedule.pdf", dayshours: ""},
             %FoodTruck{applicant: "Senor Sisig", facility_type: "Truck", location_description: "CALIFORNIA ST: DAVIS ST to FRONT ST (100 - 199)", address: "101 CALIFORNIA ST", status: "APPROVED", food_items: "Senor Sisig: Filipino fusion food: tacos: burritos: nachos: rice plates. Various beverages.", latitude: "37.792948952834664", longitude: "-122.39809861316652", schedule: "http://bsm.sfdpw.org/PermitsTracker/reports/report.aspx?title=schedule&report=rptSchedule&params=permit=22MFF-00043&ExportPDF=1&Filename=22MFF-00043_schedule.pdf", dayshours: ""},
             %FoodTruck{applicant: "Senor Sisig", facility_type: "Truck", location_description: "MISSION ST: 05TH ST to MINT ST (900 - 930)", address: "901 MISSION ST", status: "APPROVED", food_items: "Senor Sisig: Filipino fusion food: tacos: burritos: nachos: rice plates. Various beverages.", latitude: "37.78215364099855", longitude: "-122.40660110683912", schedule: "http://bsm.sfdpw.org/PermitsTracker/reports/report.aspx?title=schedule&report=rptSchedule&params=permit=22MFF-00043&ExportPDF=1&Filename=22MFF-00043_schedule.pdf", dayshours: ""}
           ]
  end
end
